/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        primary: 'var(--primary)',
        'primary-hover': 'var(--primary-hover)',
        'secondary-bg': 'var(--secondary-bg)',
        border: 'var(--border)',
        success: 'var(--success)',
        warning: 'var(--warning)',
        danger: 'var(--danger)',
        'card-bg': 'var(--card-bg)',
        'card-hover': 'var(--card-hover)',
        'header-bg': 'var(--header-bg)',
        'sidebar-bg': 'var(--sidebar-bg)',
        // MTG colors
        mtg: {
          white: '#f9fafb',
          blue: '#2563eb',
          black: '#1f2937',
          red: '#dc2626',
          green: '#16a34a',
        },
      },
      fontFamily: {
        sans: ['Inter', 'Arial', 'Helvetica', 'sans-serif'],
      },
      boxShadow: {
        card: '0 2px 4px rgba(0, 0, 0, 0.05), 0 1px 2px rgba(0, 0, 0, 0.1)',
      },
      animation: {
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
    },
  },
  plugins: [],
  corePlugins: {
    preflight: true,
    container: true,
    space: true,
    divideWidth: true,
    divideColor: true,
    divideStyle: true,
    divideOpacity: true,
    accessibility: true,
    appearance: true,
    backgroundAttachment: true,
    backgroundClip: true,
    backgroundColor: true,
    backgroundImage: true,
    backgroundOpacity: true,
    backgroundPosition: true,
    backgroundRepeat: true,
    backgroundSize: true,
    borderCollapse: true,
    borderColor: true,
    borderOpacity: true,
    borderRadius: true,
    borderStyle: true,
    borderWidth: true,
    boxShadow: true,
    boxSizing: true,
    cursor: true,
    display: true,
    flexDirection: true,
    flexWrap: true,
    placeItems: true,
    placeContent: true,
    placeSelf: true,
    alignItems: true,
    alignContent: true,
    alignSelf: true,
    justifyItems: true,
    justifyContent: true,
    justifySelf: true,
    flex: true,
    flexGrow: true,
    flexShrink: true,
    order: true,
    float: true,
    clear: true,
    fontFamily: true,
    fontWeight: true,
    height: true,
    fontSize: true,
    lineHeight: true,
    listStylePosition: true,
    listStyleType: true,
    margin: true,
    maxHeight: true,
    maxWidth: true,
    minHeight: true,
    minWidth: true,
    objectFit: true,
    objectPosition: true,
    opacity: true,
    outline: true,
    overflow: true,
    overscrollBehavior: true,
    padding: true,
    placeholderColor: true,
    placeholderOpacity: true,
    pointerEvents: true,
    position: true,
    inset: true,
    resize: true,
    fill: true,
    stroke: true,
    strokeWidth: true,
    tableLayout: true,
    textAlign: true,
    textColor: true,
    textOpacity: true,
    textOverflow: true,
    textDecoration: true,
    textTransform: true,
    userSelect: true,
    verticalAlign: true,
    visibility: true,
    whitespace: true,
    width: true,
    wordBreak: true,
    zIndex: true,
    gap: true,
    gridAutoFlow: true,
    gridTemplateColumns: true,
    gridAutoColumns: true,
    gridColumn: true,
    gridColumnStart: true,
    gridColumnEnd: true,
    gridTemplateRows: true,
    gridAutoRows: true,
    gridRow: true,
    gridRowStart: true,
    gridRowEnd: true,
    transform: true,
    transformOrigin: true,
    scale: true,
    rotate: true,
    translate: true,
    skew: true,
    transitionProperty: true,
    transitionTimingFunction: true,
    transitionDuration: true,
    transitionDelay: true,
    animation: true,
  }
}
